apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot
  labels:
    app: robot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robot
  template:
    metadata:
      labels:
        app: robot
    spec:
      containers:
      - name: robot
        image: csuszka01/edfrobotcontainer:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http-reset
        command: ["./myapp","100","100", "true"]  # Substitute timeout and fps here and debug flag
      nodeSelector:
        job: "robot"
